LOAD DATA INFILE 'snake.tab' INTO TABLE snake;
LOAD DATA INFILE 'country.tab' INTO TABLE country FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n';
LOAD DATA INFILE 'lives_in.tab' INTO TABLE lives_in FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n';