LOAD DATA LOCAL INFILE '../data/snake.tab' INTO TABLE snake FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE '../data/country.tab' INTO TABLE country FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE '../data/lives_in.tab' INTO TABLE lives_in FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n';